<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXtmNB0\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXtmNB0/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXXtmNB0.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXXtmNB0\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXXtmNB0\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XXtmNB0',
    'container.build_id' => 'aae0d629',
    'container.build_time' => 1529496439,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXtmNB0');
